[package]
name = "rgen-placer"
version = "0.1.0"
edition = "2024"

[dependencies]
rgen-base.workspace = true
rgen-llama.workspace = true
rgen-world.workspace = true
rgen-spline.workspace = true

log = "0.4.22"

[[bench]]
name = "noise"
