name: java

on:
  pull_request:

jobs:
  integration:
    name: integration
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          distribution: corretto
          java-version: 8
      - uses: gradle/actions/setup-gradle@v4
      - run: ./gradlew build
      - run: rustup update stable && rustup default stable
      - run: |
          cd rgen
          cargo build -p rgen-jni-impl -p rgen-jni --release
      - run: ./setup-server.sh
      - run: ./start-server.sh
